Feature#33 login function
BC-MAY-21-ROR/kata-06-reloj-checador-k06-t04 pull request #39
Opened 2021-07-21 02:06 UTC by SampabloC

# Description
What did you implemented/Why did you implemented this:
 - Add login function to administrator using bcrypt gem.
 - What? Create session when administrator log in and destroy it when log out.
 -  Why? To avoid users not logged it modify restricted data.
 - Add an alert when log in is wrong for email or password.
 - Add personalize message when administrator log in to show a welcome message.
 
Resolve #33 
 
 # Testing
 - I add an administrator with email 'admin@admin.com' and password '1234', this is include on seed file.

 ## Screenshots 
Alert to wrong log in.
![imagen](https://user-images.githubusercontent.com/38772008/126418995-dda88392-83d6-4517-8e7e-a71c1fdc4815.png)

Welcome message to administrator.
![imagen](https://user-images.githubusercontent.com/38772008/126419161-29f0113e-22d9-4e7d-b317-31a5b054b4a8.png)

2021-07-21 02:12 UTC, AlejandroVI99 approved these changes, later dismissed
Nice!

2021-07-21 02:32 UTC, SEVERO96 approved these changes, later dismissed

2021-07-21 02:36 UTC, SEVERO96 commented
Interesting gem, just out of curiosity, why didn't you use the devise gem? Blessings.

2021-07-21 23:48 UTC, YilKanda requested changes
Remember that GitHub tells us when to leave a blank line (with a symbol of a circle with a red line in the middle.), and those codes that do not occupy can be eliminated (I mean the commented codes).

And if the visual part can be improved, it would be much better. (This can be considered for another issue)

2021-07-21 23:48 UTC, YilKanda commented on app/views/sessions/validation.html.erb
> +<% end %>
Add a blank line

2021-07-21 23:48 UTC, YilKanda commented on app/views/administrators/check.html.erb
>    </p>
Add a blank line

2021-07-21 23:48 UTC, YilKanda commented on db/seeds.rb
> +# end
If you don't occupy them, delete them.

2021-07-22 18:49 UTC, AlejandroVI99 approved these changes
LGTM JAVIER!

2021-07-22 19:52 UTC, xFerchoVJ approved these changes

2021-07-22 21:01 UTC, martinmt-mx approved these changes

2021-07-22 21:08 UTC, SEVERO96 approved these changes

2021-07-22 23:07 UTC, YilKanda approved these changes

2021-07-22 23:16 UTC, merged